server {
    listen 80;
    server_name start.gntm.club;

    location / {
        proxy_pass http://10.0.16.16:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}